CREATE DATABASE [TaskManagerDB]
GO

USE [TaskManagerDB]
GO

CREATE TABLE [Task]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[Descripcion] NVARCHAR(100) NOT NULL,
	[FechaCreacion] DATETIME NOT NULL,
	[Estado] VARCHAR(10) NOT NULL,
	[Prioridad] INT NOT NULL,

	CONSTRAINT PK_TASK PRIMARY KEY ([Id])
)
GO